.TH openscribe 1
.SH NAME
OpenScribe \- transcribe audio files using a USB footpedal
.SH SYNOPSIS
.B openscribe
[\fIfile\fR]
.SH DESCRIPTION
.B OpenScribe
is an application to aid transcriptionists in transcribing audio dictations. Audio playback may be controlled using a USB input device such as a footpedal or hand control. See the in-program help section for instructions on using this application.
.SH AUTHORS
OpenScribe is written and maintained by Matt Pharoah.
.PP
OpenScribe uses the Sonic library, which was written by Bill Cox, to slow down audio. OpenScribe also makes use of SoX, PulseAudio, and GTK+.

